### ISSUE TITLE
mount start fails

### ISSUE THREAD

**Issue by WorldsEndless** [Otann/garden-gnome#1]
Attempting mount.core/start after following the examples in the readme fails; it compiles once and throws an error. 

>   Show: Project-Only All 
>   Hide: Clojure Java REPL Tooling Duplicates  (14 frames hidden)
> 
> 2. Unhandled java.lang.RuntimeException
>    could not start [#'lineal.style/garden] due to
> 
>                  core.cljc:   92  mount.core$up$fn__100/invoke
>                  core.cljc:   92  mount.core$up/invokeStatic
>                  core.cljc:   90  mount.core$up/invoke
>                  core.cljc:  210  mount.core$bring/invokeStatic
>                  core.cljc:  202  mount.core$bring/invoke
>                  core.cljc:  252  mount.core$start/invokeStatic
>                  core.cljc:  244  mount.core$start/doInvoke
>                RestFn.java:  397  clojure.lang.RestFn/invoke
>                       REPL:  117  lineal.linear/eval51133
>                       REPL:  117  lineal.linear/eval51133
>              Compiler.java: 6927  clojure.lang.Compiler/eval
>              Compiler.java: 6890  clojure.lang.Compiler/eval
>                   core.clj: 3105  clojure.core/eval
>                   core.clj: 3101  clojure.core/eval
>                   main.clj:  240  clojure.main/repl/read-eval-print/fn
>                   main.clj:  240  clojure.main/repl/read-eval-print
>                   main.clj:  258  clojure.main/repl/fn
>                   main.clj:  258  clojure.main/repl
>                   main.clj:  174  clojure.main/repl
>                RestFn.java: 1523  clojure.lang.RestFn/invoke
>     interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
>                   AFn.java:  152  clojure.lang.AFn/applyToHelper
>                   AFn.java:  144  clojure.lang.AFn/applyTo
>                   core.clj:  646  clojure.core/apply
>                   core.clj: 1881  clojure.core/with-bindings*
>                   core.clj: 1881  clojure.core/with-bindings*
>                RestFn.java:  425  clojure.lang.RestFn/invoke
>     interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
>     interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
>     interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
>     interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
>                   AFn.java:   22  clojure.lang.AFn/run
>    ThreadPoolExecutor.java: 1149  java.util.concurrent.ThreadPoolExecutor/runWorker
>    ThreadPoolExecutor.java:  624  java.util.concurrent.ThreadPoolExecutor$Worker/run
>                Thread.java:  748  java.lang.Thread/run
> 
> 1. Caused by java.lang.NullPointerException
>    (No message)
> 
>                   core.clj:   15  hawk.core/extract-paths-by-type/fn
>                   core.clj: 2646  clojure.core/map/fn
>               LazySeq.java:   40  clojure.lang.LazySeq/sval
>               LazySeq.java:   49  clojure.lang.LazySeq/seq
>                    RT.java:  521  clojure.lang.RT/seq
>                   core.clj:  137  clojure.core/seq
>              protocols.clj:   24  clojure.core.protocols/seq-reduce
>              protocols.clj:   75  clojure.core.protocols/fn
>              protocols.clj:   75  clojure.core.protocols/fn
>              protocols.clj:   13  clojure.core.protocols/fn/G
>                   core.clj: 6545  clojure.core/reduce
>                   core.clj: 6860  clojure.core/group-by
>                   core.clj: 6860  clojure.core/group-by
>                   core.clj:   16  hawk.core/extract-paths-by-type
>                   core.clj:   12  hawk.core/extract-paths-by-type
>                   core.clj:   71  hawk.core/watch!/fn/fn
>                   core.clj: 2644  clojure.core/map/fn
>               LazySeq.java:   40  clojure.lang.LazySeq/sval
>               LazySeq.java:   56  clojure.lang.LazySeq/seq
>                    RT.java:  521  clojure.lang.RT/seq
>                   core.clj:  137  clojure.core/seq
>                   core.clj: 2637  clojure.core/map/fn
>               LazySeq.java:   40  clojure.lang.LazySeq/sval
>               LazySeq.java:   49  clojure.lang.LazySeq/seq
>                    RT.java:  521  clojure.lang.RT/seq
>                   core.clj:  137  clojure.core/seq
>                   core.clj:  641  clojure.core/apply
>                   core.clj: 2674  clojure.core/mapcat
>                   core.clj: 2674  clojure.core/mapcat
>                RestFn.java:  423  clojure.lang.RestFn/invoke
>                   core.clj:   76  hawk.core/watch!
>                   core.clj:   59  hawk.core/watch!
>                RestFn.java:  410  clojure.lang.RestFn/invoke
>                watcher.clj:   60  garden-gnome.watcher/start!
>                watcher.clj:   52  garden-gnome.watcher/start!
>                       REPL:   10  lineal.style/eval51033/fn
>                  core.cljc:   86  mount.core$record_BANG_/invokeStatic
>                  core.cljc:   85  mount.core$record_BANG_/invoke
>                  core.cljc:   93  mount.core$up$fn__100/invoke
>                  core.cljc:   92  mount.core$up/invokeStatic
>                  core.cljc:   90  mount.core$up/invoke
>                  core.cljc:  210  mount.core$bring/invokeStatic
>                  core.cljc:  202  mount.core$bring/invoke
>                  core.cljc:  252  mount.core$start/invokeStatic
>                  core.cljc:  244  mount.core$start/doInvoke
>                RestFn.java:  397  clojure.lang.RestFn/invoke
>                       REPL:  117  lineal.linear/eval51133
>                       REPL:  117  lineal.linear/eval51133
>              Compiler.java: 6927  clojure.lang.Compiler/eval
>              Compiler.java: 6890  clojure.lang.Compiler/eval
>                   core.clj: 3105  clojure.core/eval
>                   core.clj: 3101  clojure.core/eval
>                   main.clj:  240  clojure.main/repl/read-eval-print/fn
>                   main.clj:  240  clojure.main/repl/read-eval-print
>                   main.clj:  258  clojure.main/repl/fn
>                   main.clj:  258  clojure.main/repl
>                   main.clj:  174  clojure.main/repl
>                RestFn.java: 1523  clojure.lang.RestFn/invoke
>     interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
>                   AFn.java:  152  clojure.lang.AFn/applyToHelper
>                   AFn.java:  144  clojure.lang.AFn/applyTo
>                   core.clj:  646  clojure.core/apply
>                   core.clj: 1881  clojure.core/with-bindings*
>                   core.clj: 1881  clojure.core/with-bindings*
>                RestFn.java:  425  clojure.lang.RestFn/invoke
>     interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
>     interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
>     interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
>     interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
>                   AFn.java:   22  clojure.lang.AFn/run
>    ThreadPoolExecutor.java: 1149  java.util.concurrent.ThreadPoolExecutor/runWorker
>    ThreadPoolExecutor.java:  624  java.util.concurrent.ThreadPoolExecutor$Worker/run
>                Thread.java:  748  java.lang.Thread/run

I get the same error when I'm not really defining a style at all:

```
(ns lineal.style
  (:require [garden.def :refer [defstylesheet defstyles defkeyframes]]
            [garden.units :as u :refer [px]]
            [garden.color :as c :refer [hex->hsl hsl->hex hsl hsla]] ;:rename {hex->rgb hr, rgb->hex rh}]
            [garden.selectors :as s :refer [nth-child defpseudoclass defpseudoelement]]))

(defstyles lineal
  [:body {:color "red"}])
```

my project.clj has:
```
  :garden {:builds [{:id "lineal"
                     :source-paths ["src/clj"]
                     ;; The var containing your stylesheet:
                     :stylesheet lineal.style/lineal
                     :compiler {:output-to "resources/public/css/style.css"
                                :pretty-print? true}}]}
```

**Comment by Otann** [comment]
@WorldsEndless Hi! Thank you for posting this.

I see in the configuration you have `:source-paths` and it's a vector.
In the latest version it should be a string and in singular — `:source-path`

This confusion may come from the fact that it was like that for some time, but then I decided to change it for a plain string since you can store symbol only in one folder ;)

Could you try that and check if it works?

**Comment by WorldsEndless** [comment]
Ah! Yes, that did it: changing :source-paths ["string"] to :source-path "string" . This represents a change in the parameters I've used for Garden for the past 2 years. Thanks!

**Comment by wesleyhall** [comment]
@Otann 

Love the project, but I have to question this change. While you are quite right, you can only put the entry symbol in one place, this does make the configuration incompatible with lein-garden, which expects a vector :source-paths (and crashes out if you don't have this). 

This means that the little piece of text in the readme for the project that says, "same format as lein-garden", is no longer true, and means that if you want to use lein-garden to compile for release, and gnome for development with figwheel, then you need both keys in the config map, which is a bit of a wart.
